Repository FACxBeamery/grads-final-project, pull requests merged in 2019-12, with the labels that each got.

#16 Tom survey editor
  .travis.yml
  client/package-lock.json
  client/package.json
  client/src/components/Copyright/index.jsx
  client/src/components/Main/Main.jsx
  client/src/components/Snackbar/index.jsx
  client/src/pages/AdminLogin/AdminLogin.test.jsx
  client/src/pages/AdminLogin/__mocks__/apiCalls.js
  client/src/pages/AdminLogin/apiCalls.js
  client/src/pages/AdminLogin/index.jsx
  client/src/pages/AdminLogin/styles.js
  client/src/store/actions/adminLoginActions.js
  client/src/store/actions/snackbarActions.js
  client/src/store/index.js
  client/src/store/reducer/adminLoginReducer.js
  client/src/store/reducer/snackbarReducer.jsx
  dev-docker-compose.yml
  package-lock.json
  package.json
  server/.env
  server/.eslintrc.js
  server/app.js
  server/config/passport/index.js
  server/databaseConnection.js
  server/dummyData/dummyAdmins.js
  server/dummyData/dummyEmployees.js
  server/dummyData/dummySurveys.js
  server/handlers/getAdmins.js
  server/handlers/getAdmins.test.js
  server/handlers/postAdmins.js
  server/handlers/postLogin.js
  server/handlers/postLogin.test.js
  server/handlers/postSurveys.js
  server/handlers/postSurveys.test.js
  server/package-lock.json
  server/package.json
  server/queries/addQuestions.js
  server/queries/addQuestions.test.js
  server/queries/createSurvey.js
  server/queries/createSurvey.test.js
  server/queries/findAdminByCredentials.js
  server/queries/findAdminByCredentials.test.js
  server/queries/findAdminById.js
  server/queries/findAdminById.test.js
  server/queries/validateAdmin.js
  server/router.js
  server/server.js
  server/travis_tests.sh
  server/utils/getJWTSecret.js
  server/utils/getMONGO_URI.js
  server/utils/getNODE_ENV.js
  server/utils/mongo/getMongoUri.js
Labels: Approved

#22 Client/dashboard improvements
  client/src/pages/Dashboard/Dashboard.test.js
  client/src/pages/Dashboard/components/AllSurveysTable.jsx
  client/src/pages/Dashboard/components/AllSurveysTable.module.css
  client/src/pages/Dashboard/components/SurveyCard.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/utils/formatDate.js
  client/src/utils/formatDate.test.js
  client/src/utils/sortArrayByObjsKey.js
  client/src/utils/sortArrayByObjsKey.test.js
  server/dummyData/dummySurveys.js
Labels: Awaiting review

#21 Fix create survey
  client/src/pages/CreateSurvey/CreateSurvey.test.jsx
  client/src/pages/CreateSurvey/Options/Options.jsx
  client/src/pages/CreateSurvey/Questions/Question.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  client/src/utils/formatDate.js
Labels: Awaiting review

#25 Take survey
  client/.gitignore
  client/src/App.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Main/Main.jsx
  client/src/pages/TakeSurvey/QuestionCard/QuestionCard.jsx
  client/src/pages/TakeSurvey/SurveyDescription/SurveyDescription.jsx
  client/src/pages/TakeSurvey/SurveyDescription/SurveyDescription.test.jsx
  client/src/pages/TakeSurvey/SurveySubmit/SurveySubmit.jsx
  client/src/pages/TakeSurvey/TakeSurvey.test.jsx
  client/src/pages/TakeSurvey/UserProgressStepper/UserProgressStepper.jsx
  client/src/pages/TakeSurvey/index.jsx
  client/src/store/index.js
  client/src/store/reducer/takeSurveyReducer.js
  client/src/theme.js
  server/.gitignore
  server/dummyData/dummyQuestions.js
  server/dummyData/dummySurveys.js
  server/handlers/getSurveyAndQuestions.js
  server/handlers/patchSurveys.js
  server/handlers/postSurveys.js
  server/queries/addResponse.js
  server/queries/readSurveyAndQuestions.js
  server/router.js
Labels: Awaiting review

#26 Employee list pagination
  client/package-lock.json
  client/src/components/EmployeeTable/EmployeeTable.test.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.test.jsx
  client/src/components/EmployeeTable/index.jsx
  client/src/pages/CreateSurvey/RecipientsList/index.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/store/index.js
  client/src/store/reducer/createSurveyReducer.js
  client/src/store/reducer/employeeTableReducer.js
  server/handlers/getEmployees.js
  server/package-lock.json
  server/queries/readEmployees.js
  server/router.js
Labels: Awaiting review, Changes requested

#28 cleanup of dummy data
  server/dummyData/dummyAdmins.js
  server/dummyData/dummyEmployees.js
  server/dummyData/dummyQuestions.js
  server/dummyData/dummySurveys.js
Labels: Awaiting review

#29 Client/check if survey created
  client/src/pages/CreateSurvey/CreateSurvey.test.jsx
  client/src/pages/CreateSurvey/Options/Options.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  server/queries/readSurvey.js
  server/queries/updateSurvey.js
Labels: Awaiting review

#31 Thomas survey detail
  client/src/components/Main/Main.jsx
  client/src/pages/Dashboard/components/SurveyCard.jsx
  client/src/pages/SurveyDetail/SurveyDetail.test.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/store/actions/createSurveyActions.js
  client/src/store/actions/surveyDetailActions.js
  client/src/store/index.js
  client/src/store/reducer/surveyDetailReducer.js
  server/dummyData/dummySurveys.js
  server/handlers/getSurvey.test.js
  server/handlers/patchSurvey.test.js
  server/handlers/postSurveys.test.js
  server/queries/createSurvey.test.js
  server/queries/readSurvey.js
  server/queries/readSurvey.test.js
  server/queries/updateSurvey.test.js
Labels: Awaiting review

#33 testing adding employees
  client/src/components/EmployeeTable/EmployeeTable.test.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.test.jsx
  client/src/components/EmployeeTable/index.jsx
  client/src/pages/CreateSurvey/RecipientsList/index.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/Dashboard/components/SurveyCard.jsx
  client/src/pages/EditSurvey/EditSurvey.test.jsx
  client/src/pages/EditSurvey/index.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/pages/TakeSurvey/QuestionCard/QuestionCard.jsx
  client/src/pages/TakeSurvey/TakeSurvey.test.jsx
  client/src/pages/TakeSurvey/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  client/src/store/reducer/editSurveyReducer.js
  client/src/store/reducer/employeeTableReducer.js
  client/src/store/reducer/surveyDetailReducer.js
  client/src/store/reducer/takeSurveyReducer.js
  server/dummyData/dummyEmployees.js
  server/handlers/getSurvey.js
  server/queries/updateSurvey.js
  server/utils/getJWTSecret.js
Labels: Awaiting review

#23 Jwt authentication login page
  .travis.yml
  client/src/components/Main/Main.jsx
  client/src/components/Snackbar/index.jsx
  client/src/pages/AdminLogin/__mocks__/apiCalls.js
  client/src/pages/AdminLogin/apiCalls.js
  client/src/pages/AdminLogin/index.jsx
  client/src/pages/AdminLogin/styles.js
  client/src/store/actions/adminLoginActions.js
  client/src/store/actions/snackbarActions.js
  client/src/store/reducer/adminLoginReducer.js
  client/src/store/reducer/snackbarReducer.jsx
  package-lock.json
  package.json
  server/.env
  server/.eslintrc.js
  server/app.js
  server/config/passport/index.js
  server/databaseConnection.js
  server/dummyData/dummyEmployees.js
  server/dummyData/dummyQuestions.js
  server/handlers/getAdmins.js
  server/handlers/getAdmins.test.js
  server/handlers/postLogin.js
  server/handlers/postLogin.test.js
  server/package-lock.json
  server/package.json
  server/queries/addQuestions.js
  server/queries/addQuestions.test.js
  server/queries/findAdminByCredentials.test.js
  server/queries/findAdminById.js
  server/queries/findAdminById.test.js
  server/router.js
  server/travis_tests.sh
  server/utils/getJWTSecret.js
  server/utils/getMONGO_URI.js
  server/utils/getNODE_ENV.js
Labels: Awaiting review

#39 Client/improvements dashboard
  client/src/pages/Dashboard/Dashboard.test.js
  client/src/pages/Dashboard/components/AllSurveysTable.module.css
  client/src/pages/Dashboard/components/SurveyCard.jsx
  client/src/pages/Dashboard/components/SurveyCard.module.css
  client/src/pages/Dashboard/index.jsx
  client/src/pages/EditSurvey/EditSurvey.test.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/store/reducer/surveyDetailReducer.js
  server/dummyData/dummySurveys.js
  server/handlers/patchSurvey.test.js
  server/handlers/postSurveys.js
  server/queries/updateSurvey.test.js
Labels: Awaiting review

#40 set up eslint on server
  server/databaseConnection.js
  server/handlers/getEmployees.js
  server/handlers/getSurvey.js
  server/handlers/getSurvey.test.js
  server/handlers/patchSurvey.test.js
  server/handlers/postLogin.test.js
  server/handlers/postSurveys.js
  server/handlers/postSurveys.test.js
  server/package-lock.json
  server/package.json
  server/queries/addQuestions.test.js
  server/queries/addResponse.js
  server/queries/createSurvey.js
  server/queries/createSurvey.test.js
  server/queries/readEmployees.js
  server/queries/readSurvey.js
  server/queries/readSurvey.test.js
  server/queries/readSurveyAndQuestions.js
  server/queries/readSurveys.js
  server/queries/updateSurvey.js
  server/queries/updateSurvey.test.js
  server/router.js
  server/server.js
  server/travis_tests.sh
  server/utils/getJWTSecret.js
  server/utils/getMONGO_URI.js
  server/utils/getNODE_ENV.js
  server/utils/mongo/getMongoUri.js
Labels: Awaiting review

#45 Create survey from template
  client/src/components/EmployeeTable/index.jsx
  client/src/components/Main/Main.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/Dashboard/components/AllSurveysTable.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/pages/SurveyBuilderFromTemplate/SurveyBuilderFromTemplate.test.jsx
  client/src/pages/SurveyBuilderFromTemplate/components/TemplateSurveysTable.jsx
  client/src/pages/SurveyBuilderFromTemplate/components/TemplateSurveysTable.module.css
  client/src/pages/SurveyBuilderFromTemplate/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  client/src/store/reducer/dashboardReducer.js
Labels: Awaiting review

#46 Thomas survey detail test
  client/src/pages/SurveyDetail/SurveyDetail.test.jsx
  client/src/pages/SurveyDetail/index.jsx
Labels: Awaiting review

#49 form errors' bag and (un)controlled inputs bug fix
  client/src/components/EmployeeTable/TableFilters/TableFilters.jsx
  client/src/pages/AdminLogin/index.jsx
  client/src/pages/CreateSurvey/Options/Options.jsx
  client/src/pages/CreateSurvey/Questions/Question.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/pages/EditSurvey/index.jsx
  client/src/pages/TakeSurvey/QuestionCard/QuestionCard.jsx
  client/src/store/index.js
  client/src/store/reducer/errorsBagReducer.js
Labels: Awaiting review

#44 Slack integration new
  client/src/components/Header/Header.jsx
  client/src/components/SlackModal/SlackModal.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/pages/TakeSurvey/QuestionCard/QuestionCard.jsx
  client/src/pages/TakeSurvey/SurveyDescription/SurveyDescription.jsx
  client/src/pages/TakeSurvey/UserProgressStepper/UserProgressStepper.jsx
  client/src/pages/TakeSurvey/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  client/src/store/reducer/surveyDetailReducer.js
  package.json
  server/.env
  server/databaseConnection.js
  server/dummyData/dummySurveys.js
  server/handlers/getAdmins.test.js
  server/handlers/getEmployees.js
  server/handlers/getSurvey.js
  server/handlers/getSurvey.test.js
  server/handlers/getSurveyAndQuestions.test.js
  server/handlers/patchSurvey.test.js
  server/handlers/postLogin.test.js
  server/handlers/postSlackMessage.js
  server/handlers/postSurveys.test.js
  server/package.json
  server/queries/addQuestions.test.js
  server/queries/addSlackInfo.js
  server/queries/createSurvey.test.js
  server/queries/findAdminByCredentials.test.js
  server/queries/findAdminById.test.js
  server/queries/readEmployees.js
  server/queries/readSurvey.js
  server/queries/readSurvey.test.js
  server/queries/readSurveyAndQuestions.js
  server/queries/updateEmployeesWithSlackID.js
  server/queries/updateEmployeesWithSlackID.test.js
  server/queries/updateSurvey.js
  server/queries/updateSurvey.test.js
  server/router.js
  server/utils/getSLACK_OAUTH.js
  server/utils/sendSlackMessage.js
Labels: Awaiting review, bug

#54 Question options errors bag
  client/src/pages/CreateSurvey/Options/Options.jsx
  client/src/pages/CreateSurvey/Questions/Question.jsx
  client/src/pages/CreateSurvey/index.jsx
  client/src/pages/EditSurvey/index.jsx
  client/src/store/reducer/errorsBagReducer.js
Labels: Awaiting review

#57 Improvements on 'Page Not Found'
  client/src/components/Header/Header.jsx
  client/src/pages/PageNotFound/PageNotFound.test.jsx
  client/src/pages/PageNotFound/PageNotFoundImage.jsx
  client/src/pages/PageNotFound/index.jsx
Labels: Awaiting review

#50 Protected pages
  client/package.json
  client/src/components/LoadingWheel/LoadingWheel.module.css
  client/src/components/LoadingWheel/index.jsx
  client/src/components/Main/LoadingPageOrRedirect.jsx
  client/src/components/Main/Main.jsx
  client/src/components/Main/Main.test.jsx
  client/src/components/Main/dummyData/dummyData.js
  client/src/components/Main/routes.js
  client/src/pages/AdminLogin/AdminLogin.test.jsx
  client/src/pages/AdminLogin/eventHandlers.js
  client/src/pages/AdminLogin/index.jsx
  client/src/pages/LoadingPage/index.jsx
  client/src/pages/LoadingPage/styles.js
  client/src/store/actions/mainActions.js
  client/src/store/index.js
  client/src/store/reducer/mainReducer.js
  client/src/utils/addAuthorizationHeaderToEveryRequest.js
  client/src/utils/checkTokenIsAuth.js
  client/src/utils/deleteTokenOn401StatusCodes.js
  package-lock.json
  server/config/passport/index.js
Labels: Awaiting review

#58 Tom take survey
  client/src/components/Main/Main.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/pages/TakeSurvey/AlreadyCompletedMessage/AlreadyCompletedMessage.jsx
  client/src/pages/TakeSurvey/SurveyClosedMessage/SurveyClosedMessage.jsx
  client/src/pages/TakeSurvey/SurveySubmit/SurveySubmit.jsx
  client/src/pages/TakeSurvey/TakeSurvey.test.jsx
  client/src/pages/TakeSurvey/index.jsx
  client/src/store/reducer/takeSurveyReducer.js
  server/queries/updateSurvey.js
Labels: Awaiting review, Changes requested

#61 Styling theme
  client/src/pages/Dashboard/index.jsx
  client/src/theme.js
Labels: Awaiting review

#60 Csv import export
  client/package-lock.json
  client/package.json
  client/src/components/Main/Main.jsx
  client/src/pages/AdminLogin/index.jsx
  client/src/pages/SurveyDetail/ExportModal/index.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/store/reducer/surveyDetailReducer.js
  server/dummyData/dummySurveys.js
  server/handlers/protected/downloadCSV.js
  server/handlers/protected/downloadCSV.test.js
  server/handlers/protected/uploadCSV.js
  server/package-lock.json
  server/package.json
  server/router.js
  server/temp/.gitkeep
Labels: fix-tests

#63 Fix surveycard and disclaimer length
  client/src/pages/EditSurvey/index.jsx
  server/handlers/postSurveys.js
  server/queries/addResponse.js
  server/queries/createSurvey.js
  server/queries/updateEmployeesWithSlackID.js
  server/queries/updateSurvey.js
Labels: Awaiting review

#62 Survey details now open's snackbar through redux action
  client/src/pages/SurveyDetail/SurveyDetail.test.jsx
  client/src/pages/SurveyDetail/index.jsx
Labels: Awaiting review

#66 Redirects root url to /admin
  client/src/components/Main/Main.jsx
Labels: Awaiting review

#68 Fix edit view survey bug
  server/queries/updateSurvey.js
  server/router.js
Labels: Awaiting review

#70 Modal fix
  client/src/pages/Dashboard/components/AllSurveysTable.jsx
  client/src/pages/SurveyDetail/ExportModal/index.jsx
Labels: Awaiting review

#82 Edit survey question type bugfix
  client/src/pages/EditSurvey/index.jsx
  client/src/store/reducer/createSurveyReducer.js
Labels: Awaiting review

#83 Styling on survey description and slack modal fix
  client/src/components/Header/Header.jsx
  client/src/components/Header/Header.test.jsx
  client/src/components/SlackModalAndButton/SlackModalAndButton.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/pages/TakeSurvey/SurveyDescription/SurveyDescription.jsx
  client/src/pages/TakeSurvey/index.jsx
  client/src/store/reducer/surveyDetailReducer.js
  server/databaseConnection.js
  server/dummyData/dummySurveys.js
  server/handlers/postSlackMessage.js
  server/queries/updateEmployeesWithSlackID.js
  server/utils/sendSlackMessage.js
Labels: Approved, Awaiting review

#98 stop doublehashing
  server/queries/updateSurvey.js
Labels: Awaiting review

#99 Fix comments made in UAT about recipient table
  client/src/components/EmployeeTable/EmployeeTable.test.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.jsx
  client/src/components/EmployeeTable/TableFilters/TableFilters.test.jsx
  client/src/components/EmployeeTable/index.jsx
  client/src/pages/CreateSurvey/RecipientsList/index.jsx
  client/src/store/reducer/createSurveyReducer.js
  client/src/store/reducer/employeeTableReducer.js
Labels: Awaiting review

#100 Take survey bugs
  client/src/App.test.jsx
  client/src/components/SlackModalAndButton/SlackModalAndButton.jsx
  client/src/pages/SurveyDetail/index.jsx
  client/src/pages/TakeSurvey/QuestionCard/QuestionCard.jsx
  client/src/pages/TakeSurvey/SurveySubmit/SurveyCompletedImage.jsx
  client/src/pages/TakeSurvey/SurveySubmit/SurveySubmit.jsx
  client/src/pages/TakeSurvey/TakeSurvey.test.jsx
  client/src/pages/TakeSurvey/UserProgressStepper/UserProgressStepper.jsx
  client/src/pages/TakeSurvey/index.jsx
Labels: Awaiting review

#117 Test server handlers queries
  client/src/pages/CreateSurvey/index.jsx
  server/config/passport/index.js
  server/handlers/getEmployees.js
  server/handlers/getEmployees.test.js
  server/handlers/getSurveyAndQuestions.js
  server/handlers/getSurveyAndQuestions.test.js
  server/handlers/getSurveys.js
  server/handlers/getSurveys.test.js
  server/handlers/postEmployees.js
  server/handlers/postSlackMessage.js
  server/handlers/postSurveys.js
  server/handlers/postSurveys.test.js
  server/handlers/protected/downloadCSV.test.js
  server/handlers/testingPostSurveys.js
  server/queries/addQuestion.js
  server/queries/addRecipient.js
  server/queries/addResponse.js
  server/queries/addSlackInfo.js
  server/queries/addSurvey.js
  server/queries/addSurvey.test.js
  server/queries/createEmployees.js
  server/queries/deleteQuestion.js
  server/queries/readEmployees.test.js
  server/queries/readSurveyAndQuestions.js
  server/queries/readSurveys.test.js
  server/queries/removeRecipient.js
  server/queries/updateEmployeesWithSlackID.test.js
  server/queries/updateProperty.js
  server/queries/updateQuestionPosition.js
  server/queries/updateQuestions.js
  server/queries/updateRecipientCompletionStatus.js
  server/schemas/surveySchema.js
Labels: Awaiting review
